name: product_order_app_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_svg: ^2.0.16
  any_image_view: ^1.0.6
  fluttertoast: ^8.2.8
  badges: ^3.1.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_easyloading: ^3.0.5
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
